name: POSIX

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/**

env:
  LIBRARY: safe_numerics
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: gcc-6
            cxxstd: "14,1z"
            os: ubuntu-16.04
            install: g++-6
          - toolset: gcc-7
            cxxstd: "14,17"
            os: ubuntu-18.04
          - toolset: gcc-8
            cxxstd: "14,17,2a"
            os: ubuntu-18.04
          - toolset: gcc-9
            cxxstd: "14,17,2a"
            os: ubuntu-18.04
          - toolset: gcc-10
            cxxstd: "14,17,2a"
            os: ubuntu-18.04
          - toolset: clang
            cxxstd: "14,17,2a"
            os: ubuntu-18.04
          - toolset: clang
            cxxstd: "14,17,2a"
            os: macos-11

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        if: matrix.install
        run: sudo apt install ${{matrix.install}}

      - name: Setup Boost
        run: |
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
          cd ..
          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
          git submodule update --init tools/boostdep
          python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
          ./bootstrap.sh
          ./b2 -d0 headers

      - name: Run tests
        run: |
          cd ../boost-root
          ./b2 -j3 libs/$LIBRARY/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} variant=debug,release
